spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cloth_sphere_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: Ama
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080
  
