package com.clothsphere.repository.SOM;

import com.clothsphere.model.SOM.SummaryReport;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface SummaryReportRepository extends JpaRepository<SummaryReport, Long> {

    // Find reports by type
    List<SummaryReport> findByReportTypeOrderByGeneratedAtDesc(String reportType);

    // Find reports within date range
    @Query("SELECT sr FROM SummaryReport sr WHERE sr.generatedAt BETWEEN :startDate AND :endDate ORDER BY sr.generatedAt DESC")
    List<SummaryReport> findReportsByDateRange(@Param("startDate") LocalDateTime startDate,
                                               @Param("endDate") LocalDateTime endDate);

    // Find latest report by type
    Optional<SummaryReport> findTopByReportTypeOrderByGeneratedAtDesc(String reportType);

    // Find reports by generated by user
    List<SummaryReport> findByGeneratedByOrderByGeneratedAtDesc(String generatedBy);

    // Find reports by period
    @Query("SELECT sr FROM SummaryReport sr WHERE sr.periodStart >= :startDate AND sr.periodEnd <= :endDate ORDER BY sr.generatedAt DESC")
    List<SummaryReport> findReportsByPeriod(@Param("startDate") LocalDateTime startDate,
                                            @Param("endDate") LocalDateTime endDate);
}